######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 27 14:11:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FlatTextDatabase.h FlatTextDatabaseViewer.h
SOURCES += FlatTextDatabase.cpp FlatTextDatabaseViewer.cpp main.cpp
